### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by dxp10** [peterirlam/IrlGen-Digital#1]
Hi friend, could you rate my repositories and I'll rate yours at the same time? Thanks!

**Comment by peterirlam** [comment]
Hi. I'm still adding files for this project to GH. 

Could you rate another repo of mine: KetoMe-365 (third one from the top in my repositories)?

Which of yours would you like me to rate and any specific comments or features you'd like me to focus on?

P

**Comment by dxp10** [comment]
I have evaluated all your repositories. You can rate the repository you like

**Comment by peterirlam** [comment]
Hi, thanks very much. I've never added Stars before but pretty sure that I've done it correctly - I've clicked on Star in the top right corner on all your repos and I've been added to the list.
